version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directories:
      - '/'
      - '/basic/'
      - '/solid-element/'
      - '/solid-start/'
      - '/with-farm-poku/'
      - '/with-rspack/'
      - '/with-vanila-extract/'
      - '/with-vite-pages/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      npm:
        patterns:
          - '*'
